<Project Sdk="Microsoft.NET.Sdk">
    <PropertyGroup>
        <OutputType>WinExe</OutputType>
        <TargetFramework>net10.0</TargetFramework>
        <Nullable>enable</Nullable>
    </PropertyGroup>
    <PropertyGroup Condition="'$(_IsPublishing)' == 'true'">
        <PublishAot>true</PublishAot>
        <DebugType>none</DebugType>
        <DebugSymbols>false</DebugSymbols>
    </PropertyGroup>

    <PropertyGroup>
        <ApplicationManifest>app.manifest</ApplicationManifest>
        <ApplicationIcon>logo.ico</ApplicationIcon>
    </PropertyGroup>

    <!--<ItemGroup>
      <AvaloniaResource Include="logo.ico" />
    </ItemGroup>-->

    <ItemGroup>
        <PackageReference Include="Avalonia.Desktop"/>
        <PackageReference Include="SFML.Audio"/>
    </ItemGroup>

    <ItemGroup>
        <ProjectReference Include="..\MyPitch\MyPitch.csproj"/>
    </ItemGroup>

    <ItemGroup>
        <None Update="default.sf2">
            <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
        </None>
        <None Update="libfluidsynth-3.dll">
            <CopyToOutputDirectory Condition="$([MSBuild]::IsOSPlatform('Windows'))">PreserveNewest</CopyToOutputDirectory>
        </None>
        <None Update="SDL3.dll">
            <CopyToOutputDirectory Condition="$([MSBuild]::IsOSPlatform('Windows'))">PreserveNewest</CopyToOutputDirectory>
        </None>
        <None Update="sndfile.dll">
            <CopyToOutputDirectory Condition="$([MSBuild]::IsOSPlatform('Windows'))">PreserveNewest</CopyToOutputDirectory>
        </None>
        <None Update="warm pad.sf2">
            <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
        </None>
    </ItemGroup>

    <Target Name="AfterPublishCleanup"  AfterTargets="Publish">
        <Delete Files="$(PublishDir)libcsfml-graphics.so"/>
        <Delete Files="$(PublishDir)libcsfml-graphics.so.3.0"/>
        <Delete Files="$(PublishDir)libcsfml-window.so"/>
        <Delete Files="$(PublishDir)libcsfml-window.so.3.0"/>
        <Delete Files="$(PublishDir)libsfml-graphics.so.3.0"/>
        <Delete Files="$(PublishDir)libsfml-window.so.3.0"/>
        <Delete Files="$(PublishDir)MyPitch.pdb"/>

        <Delete Files="$(PublishDir)csfml-graphics.dll"/>
        <Delete Files="$(PublishDir)csfml-graphics-3.dll"/>
        <Delete Files="$(PublishDir)csfml-window.dll"/>
        <Delete Files="$(PublishDir)csfml-window-3.dll"/>
        <Delete Files="$(PublishDir)sfml-graphics-3.dll"/>
        <Delete Files="$(PublishDir)sfml-window-3.dll"/>
    </Target>


</Project>
